name: Production

on:
  push:
    branches:
      - prod
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }} 
          username: ${{ secrets.SSH_USER }} 
          key: ${{ secrets.SSH_PRIVATE_KEY }} 

          script: |
            # Add 'set -e' to stop the script if any command fails.
            set -e

            # 1. Move to project directory
            echo "Changing directory..."
            cd /home/laravel-boilerplate/htdocs/laravel-boilerplate.vngne.tech/laravel-boilerplate

            # 2. Maintenance Mode
            echo "Activating maintenance mode..."
            php artisan down

            # 3. Pull
            echo "Pulling latest code from prod branch..."
            git pull origin main

            # 4. Install Dependencies
            echo "Installing Composer dependencies..."
            composer install --no-interaction --prefer-dist --optimize-autoloader

            # 5. Run Database Migrations
            echo "Running database migrations..."
            php artisan migrate --force

            # 6. Clear Cache
            echo "Clearing cache and creating new cache..."
            php artisan optimize:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            # 7. Exit maintenance mode
            echo "Deactivating maintenance mode..."
            php artisan up

            echo "✅ Deployment to production successful!"
